### ISSUE TITLE
precompiled libwebp.dll

### ISSUE THREAD

**Issue by milika** [Wykerd/delphi-webp#1]
Hi, great piece of useful code you did :)
But would love to have a good libwebp.dll compiled already. All my environments are setup for delphi, would hate to create another VM just for compiling one dll....

Thanks!

**Comment by Wykerd** [comment]
I'll see if I can setup a Github Action to build libwebp automatically and push it to some branch :+1:

**Comment by milika** [comment]
Great, that would be great!!!
Regards!

**Comment by SergeyZaykovskiy** [comment]
Hello.

Can you, please, share libwebp.dll

I think it would be useful

Thank you!

**Comment by Wykerd** [comment]
I have added the precompiled binaries 👍
